### ISSUE TITLE
text titles

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/gis-abm-lesson#1]
Confirm choice of 'ebola-model.nlogo' versus 'expanded-eboloa-model.nlogo'. Esp on 'Fix the Labels' subsection.

**Comment by nickmags13** [comment]
'ebola_model.nlogo' is the correct model name

**Comment by itcarroll** [comment]
Fixed by b8feaf338b4e2af94b608b564bfa1daf155404de.
